import React from 'react';
export const diffDetails = () => <div>diff distinct</div>;
export const diff_detail_0 = (p:any)=> <div>diff 0 cell diff</div>;
export const diff_detail_1 = (p:any)=> <div>diff 1 sheet diff</div>;
export const diff_detail_2 = (p:any)=> <div>diff 2 range</div>;
export const diff_detail_3 = (p:any)=> <div>diff 3 cell diff</div>;
export const diff_detail_4 = (p:any)=> <div>diff 4 sheet diff</div>;
export const diff_detail_5 = (p:any)=> <div>diff 5 range</div>;
export const diff_detail_6 = (p:any)=> <div>diff 6 cell diff</div>;
export const diff_detail_7 = (p:any)=> <div>diff 7 sheet diff</div>;
export const diff_detail_8 = (p:any)=> <div>diff 8 range</div>;
export const diff_detail_9 = (p:any)=> <div>diff 9 cell diff</div>;
export const diff_detail_10 = (p:any)=> <div>diff 10 sheet diff</div>;
export const diff_detail_11 = (p:any)=> <div>diff 11 range</div>;
export const diff_detail_12 = (p:any)=> <div>diff 12 cell diff</div>;
export const diff_detail_13 = (p:any)=> <div>diff 13 sheet diff</div>;
export const diff_detail_14 = (p:any)=> <div>diff 14 range</div>;
export const diff_detail_15 = (p:any)=> <div>diff 15 cell diff</div>;
export const diff_detail_16 = (p:any)=> <div>diff 16 sheet diff</div>;
export const diff_detail_17 = (p:any)=> <div>diff 17 range</div>;
export const diff_detail_18 = (p:any)=> <div>diff 18 cell diff</div>;
export const diff_detail_19 = (p:any)=> <div>diff 19 sheet diff</div>;